import { VehicleConfig, FuelType } from '../types/trip';

export const VEHICLE_PRESETS: Record<string, VehicleConfig> = {
  carro: {
    id: 'carro',
    name: 'Carro de Passeio / SUV',
    categoryName: 'Passeio',
    axles: 2,
    tollMultiplier: 1.0,
    defaultFuel: 'gasolina',
    defaultConsumption: 12.0,
    icon: 'Car',
  },
  moto: {
    id: 'moto',
    name: 'Motocicleta / Triciclo',
    categoryName: 'Moto',
    axles: 2,
    tollMultiplier: 0.5,
    defaultFuel: 'gasolina',
    defaultConsumption: 32.0,
    icon: 'Bike',
  },
  van: {
    id: 'van',
    name: 'Van / Utilitário Leve',
    categoryName: 'Utilitário',
    axles: 2,
    tollMultiplier: 1.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 9.5,
    icon: 'Truck',
  },
  onibus_2: {
    id: 'onibus_2',
    name: 'Ônibus (2 eixos)',
    categoryName: 'Ônibus',
    axles: 2,
    tollMultiplier: 2.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 4.2,
    icon: 'Bus',
  },
  onibus_3: {
    id: 'onibus_3',
    name: 'Ônibus (3 eixos)',
    categoryName: 'Ônibus',
    axles: 3,
    tollMultiplier: 3.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 3.4,
    icon: 'Bus',
  },
  caminhao_2: {
    id: 'caminhao_2',
    name: 'Caminhão Toco / VUC (2 eixos)',
    categoryName: 'Caminhão',
    axles: 2,
    tollMultiplier: 2.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 4.5,
    icon: 'Truck',
  },
  caminhao_3: {
    id: 'caminhao_3',
    name: 'Caminhão Truck (3 eixos)',
    categoryName: 'Caminhão',
    axles: 3,
    tollMultiplier: 3.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 3.5,
    icon: 'Truck',
  },
  caminhao_4: {
    id: 'caminhao_4',
    name: 'Caminhão Bitruck (4 eixos)',
    categoryName: 'Caminhão',
    axles: 4,
    tollMultiplier: 4.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 2.8,
    icon: 'Truck',
  },
  caminhao_5: {
    id: 'caminhao_5',
    name: 'Carreta Simples (5 eixos)',
    categoryName: 'Carreta',
    axles: 5,
    tollMultiplier: 5.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 2.4,
    icon: 'Truck',
  },
  caminhao_6: {
    id: 'caminhao_6',
    name: 'Carreta LS / Bitrem (6 eixos)',
    categoryName: 'Carreta',
    axles: 6,
    tollMultiplier: 6.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 2.1,
    icon: 'Truck',
  },
  caminhao_7_9: {
    id: 'caminhao_7_9',
    name: 'Rodotrem / Treminhão (7 a 9 eixos)',
    categoryName: 'Carreta Pesada',
    axles: 8,
    tollMultiplier: 8.0,
    defaultFuel: 'diesel_s10',
    defaultConsumption: 1.8,
    icon: 'Truck',
  },
};

export const DEFAULT_FUEL_PRICES: Record<FuelType, { label: string; price: number; unit: string }> = {
  gasolina: { label: 'Gasolina Comum', price: 6.10, unit: 'R$/L' },
  etanol: { label: 'Etanol', price: 4.05, unit: 'R$/L' },
  diesel_s10: { label: 'Diesel S10', price: 6.25, unit: 'R$/L' },
  diesel_s500: { label: 'Diesel S500', price: 5.95, unit: 'R$/L' },
  gnv: { label: 'GNV', price: 4.80, unit: 'R$/m³' },
  eletrico: { label: 'Eletricidade (kWh)', price: 1.15, unit: 'R$/kWh' },
};
